### ISSUE TITLE
Play nice with Flask factory pattern

### ISSUE THREAD

**Issue by mpnordland** [4Catalyzer/flask-resty#141]
Flask extensions can be initialized in two ways: having the app passed to them on creation, or by calling an init_app() method with the app later. This second way is useful when using the create_app factory pattern. 

flask-resty throws an AttributeError with the second method:
```
  File "/lib/python3.6/site-packages/flask_resty/api.py", line 49, in add_resource
    app = self._get_app(app)
  File "/lib/python3.6/site-packages/flask_resty/api.py", line 31, in _get_app
    app = app or self._app
AttributeError: 'Api' object has no attribute '_app'
```

**Comment by taion** [comment]
It does work – the caveat (as with most Flask extensions as far as I'm aware) is that if you use `init_app`, the app isn't bound to the extension instance (because you can call `init_app` multiple times with multiple apps), so instead you need to pass in the `app` when calling `add_resource`.

In other words, you'd do something like:

```python
api.add_resource('/widgets', WidgetView, app=app)
```

Since there's no app context while setting up routes, we can't infer the app from the current app, either.

**Comment by taion** [comment]
There was a dumb bug where we weren't actually hitting the assert one line down, and instead got that `AttributeError`, though. Resolved by https://github.com/4Catalyzer/flask-resty/pull/142.

I could add support for checking the current application context like in Flask-SQLAlchemy, but I'm not sure that makes sense at route configuration time, since you wouldn't normally have an application context there, so I think just passing in `app=app` is a good approach.

**Comment by taion** [comment]
Closing because I think this already works fine.
